spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/quis_listing;DB_CLOSE_DELAY=-1
        name:
        username: ql_user
        password:
    jpa:
        database-platform: com.manev.quislisting.domain.util.FixedH2Dialect
        database: H2
        show-sql: true

liquibase:
    contexts: dev

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024