spring:
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: elasticsearch/log
                  data: elasticsearch/data
    mail:
        host: smtp.mailgun.org
        port: 587
        username: postmaster@sandbox67303042665e45ce9550a1b47cd7e83f.mailgun.org
        password: 31491b269a32eb8b557d7f7b899038ac
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

#    thymeleaf:
#        cache: false

liquibase:
    contexts: dev

server:
    port: 8181
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

logging:
  level:
    org.springframework.web: INFO
    com.manev.quislisting: INFO
    org.hibernate: INFO

# ===================================================================
# Quis Listing specific properties
# ===================================================================
quislisting:
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 100 # Number of objects in each cache entry
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        baseUrl: http://localhost:8181
    attachment-storage-path: ./attachment_storage