spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./h2db/db/quis_listing;DB_CLOSE_DELAY=-1
        name:
        username: ql_user
        password:
    jpa:
        database-platform: com.manev.quislisting.domain.util.FixedH2Dialect
        database: H2
        show-sql: true
    mail:
        host: localhost
        port: 25
        username:
        password:
#    thymeleaf:
#        cache: false

liquibase:
    contexts: dev

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# Quis Listing specific properties
# ===================================================================
quislisting:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000