management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
    application:
        name: quis-listing
    social:
      facebook:
          app-id: 1006698042802363
          app-secret: beca4808feba16989ff73aa0c80403b2
      twitter:
        app-id: pZTGl7gtpEg3vcjyoK7WNsRin
        app-secret: 4mbAoQXdubouVvKe87KK7W7UOncqKcYiy7hNrcMCbx3qaDKloX
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev,dev_mariadb,swagger
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.enable_lazy_load_no_trans: true
    mvc:
        favicon:
            enabled: true
    thymeleaf:
        prefix: /templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
        template-resolver-order: 1

    http:
      multipart:
        max-file-size: 50MB
    messages:
      basename: messages, bean-validation-messages
endpoints:
    shutdown:
        enabled: true
        sensitive: false

logging:
  file: ./logs/quis.log

# ===================================================================
# Quis Listing specific properties
# ===================================================================
quislisting:
    social:
        redirect-after-sign-in: "/"
    twitter:
        access-token: 2510170801-mFO3fleqTQoHLllRMncfYcRuoLH2i5YYRljtRSX
        access-token-secret: kGwd0SXrqyZt0E7QvEbexikPAPdYYw4hLlws4AOnc1zgm
    ribbon:
        # comma separated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
    mail:
        from: QuisListing.com <contact@quislisting.com>
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    geo-location-db-path: ./geolite2/GeoLite2-Country.mmdb

security:
  oauth2:
    client:
      clientId: 124573898319-pfqf134siljgpfdlc2uo03mn98lk659v.apps.googleusercontent.com
      clientSecret: I9VmqNaLq-t75IUJ-zZghJoa
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
