management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
    application:
        name: quis-listing
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev,swagger
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.enable_lazy_load_no_trans: true
    mvc:
        favicon:
            enabled: true
    thymeleaf:
        prefix: /templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
        template-resolver-order: 1

    http:
      multipart:
        max-file-size: 50MB
    messages:
      basename: messages, bean-validation-messages
endpoints:
    shutdown:
        enabled: true
        sensitive: false

logging:
  file: ./logs/quis.log

# ===================================================================
# Quis Listing specific properties
# ===================================================================
quislisting:
    ribbon:
        # comma separated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
    mail:
        from: contact@quislisting.com
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    attachment-storage-path: ./attachment_storage